### PR TITLE
CLSAG fuzzer size checks

### PR DESCRIPTION
**Pull request by unseddd**
Basic size checks for CLSAG fuzzer functions.

Minor fixes for compiling unit-tests.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Thanks, looks like there is no CLSAG fuzz test in the tree, must have forgot to PR it, I'll do that now.

Send any further patch to monero-project/bitmonero, I'll never look here again, I saw this by chance, this is just my fork.

**Comment by moneromooo-monero** [comment]
Now in the tree, but it runs a < one/second, which is atrocious and unlikely to get anywhere soon :/
Not sure I want to PR that tbh.

**Comment by moneromooo-monero** [comment]
And I'll likely forget about this soon, so if you reply, IRC's probably best :D

**Comment by unseddd** [comment]
> And I'll likely forget about this soon, so if you reply, IRC's probably best :D

No worries, will reach out on IRC if anything comes up.

> Now in the tree, but it runs a < one/second, which is atrocious and unlikely to get anywhere soon :/

Yeah, that's pretty terrible performance. Can't remember exactly what the time sink is, but can take a look. Feel free to not PR.

I've learned more about how fuzzers work since writing the CLSAG fuzzer, so I'll take a look. Maybe get the perf closer to 100-1000/sec :D

**Pull request closed without merging**
